// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"crawlergo/internal/biz"
	"crawlergo/internal/conf"
	"crawlergo/internal/data"
	"crawlergo/pkg/task"
)

// Injectors from wire.go:

func wireRedisCacheRepo(taskConfig task.TaskConfig) *biz.EngineUsecase {
	redisConf := conf.NewRedisConf(taskConfig)
	dataData := data.NewData(redisConf)
	engineRepo := data.NewEngineRepo(dataData, redisConf)
	engineUsecase := biz.NewEngineUsecase(engineRepo, taskConfig)
	return engineUsecase
}
